FROM ubuntu:24.04

COPY apt/ /apt/
RUN apt-get update && apt-get install bash

# Install dependencies
WORKDIR /apt/
RUN chmod +x ./install.sh
RUN ./install.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/Code

# Create volumes for local code
