name = "Example"

apt = [<package_1>, <package_2>, ...]

[spack]
lockfile = <spack lock-file path>

# Both url and copy are optional
[deps.foo-dependency]
filepath = <filepath>
url = <source-url>  # If the local repository has a defined remote named origin,
                    # the program will find the url automatically
copy = <bool> # Defaults to True if omitted

[deps.bar-dependency] # Will be copied
filepath = <filepath>

[deps.bar-dependency] # Will be stored as commit hash
filepath = <filepath>
url = <source-url>
copy = false
