name = "Example"

apt = [<package_1>, <package_2>, ...]

[spack]
lockfile = <spack lock-file path>

# Both url and copy are optional
[deps.foo-dependency]
filepath = <filepath>
url = <github:url>
copy = <bool> # Defaults to True if omitted

[deps.bar-dependency]
filepath = <filepath>
url = <github:url>

