name = "Example"
apt = [<package_1>, <package_2>, ...]

[spack]
lockfile = <spack lock-file path>

# Both url and filepath are optional, but at least one needs to be there. Two
# also works
[deps.foo-dependency]
url = <github:url>
filepath = <filepath>
copy = <bool> # Defaults to True

[deps.bar-dependency]
url = <github:url>
filepath = <filepath>

